default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/size_matters_development

test:
  <<: *default
  database: db/size_matters_test

production:
  <<: *default
  database: size_matters_production
  username: size_matters
  password: <%= ENV['SIZE_MATTERS_DATABASE_PASSWORD'] %>
