question = Question.create!(text: "0.5\" wide crack upper body size")
question.answers.create!(text: "Fingers")
question.answers.create!(text: "Hands")
question.answers.create!(text: "Fists")
question.answers.create!(text: "Off-width")
